checkout_cashbox:
  path: /
  controller:  BSApp\Controller\cashboxController:indexAction

cashbox_quickbutton:
  path: /
  controller:  BSApp\Controller\quickbuttonController:indexAction

cashbox_quickbutton_show:
  path: /{id}/show
  controller:  BSApp\Controller\quickbuttonController:showAction

cashbox_quickbutton_new:
  path: /new
  controller:  BSApp\Controller\quickbuttonController:newAction


cashbox_quickbutton_create:
  path: /create
  methods: POST
  #      * @Template("BSCheckoutBundle:quickbutton:new.html.twig")
  controller:  BSApp\Controller\quickbuttonController:createAction


cashbox_quickbutton_edit:
  path: /{id}/edit
  controller:  BSApp\Controller\quickbuttonController:editAction


cashbox_quickbutton_update:
  path: /{id}/update
  controller:  BSApp\Controller\quickbuttonController:updateAction


cashbox_quickbutton_delete:
  path: /{id}/delete
  methods: POST
  controller:  BSApp\Controller\quickbuttonController:deleteAction
