<?php

namespace Acme\BSDataBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * stockkeepingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class stockkeepingRepository extends EntityRepository
{
}
